### ISSUE TITLE
[Bug] Cannot detect glist workspace

### ISSUE THREAD

**Issue by sorbatdev** [javertus/GlistEngine-vscode-extension#1]
| name | about | title | labels | assignees |
| --- | --- | ---| --- | --- |
| Bug report | Workspace detection | "[Bug]" | bug | @sorbatdev | 

 - OS: Windows

**Describe the bug**</br>
Create new project command giving error message when glist folder is open.

**To Reproduce**</br>
1. Open 'glist' folder inside VS Code under .../dev/
2. Open Command Palette and select: `Glist Engine: Create New Project`
3. Get error text: `You should switch to Glist workspace to do that.` 

**Expected behavior**</br>
Should not get the error message while in glist directory.

**Screenshots**</br>

**Additional context**</br>

The problem seems to be caused by this line. VS code may not register the GlistEngine directory in folders as the `len - 1`th folder. Should instead search the `folders` variable and see if a entry with glist engine exists.
https://github.com/javertus/GlistEngine-vscode-extension/blob/c817dff8a18db1ae54aa013380a021d0c2ab9bec/src/WorkspaceProcesses.ts#L13

**Comment by javertus** [comment]
You should not open the workspace by yourself.. You need to execute the `Glist Engine: Switch to Workspace` command for that. Also, Isn't the workspace automatically launched when you installed the extension?

**Comment by sorbatdev** [comment]
No, it didn't. `Glist Engine: Switch to Workspace` also gave a `Failed to create workspace.` error. Had no folders open in workspace when i got the error.

**Comment by javertus** [comment]
I have no idea what is wrong..  `Glist Engine: Switch to Workspace` command was should be worked as expected. However, I'm going to update the extension with a few changes so it will output the full error when you execute the `Glist Engine: Switch to Workspace` command then you can see what is wrong.

**Comment by javertus** [comment]
Can you check the issue again? @sorbatdev

**Comment by javertus** [comment]
This issue was occurred because your glist installation is not in same disk with the extension's working disk. Issue is fixed on update 1.3.5
